var _ = require("../src/help.js"),
assert = require("assert");
assert.notEqual(_.isComment.exec("; wrwtew"), null);
assert.notEqual(_.isComment.exec("; wrwtew\n wfewf"), null);
assert.equal(_.isComment.exec("  ; wrwtew"), null);
assert.equal(_.isComment.exec("\"wat\""), null);
assert.equal(_.isComment.exec("("), null);
assert.notEqual(_.isSpace.exec("  "), null);
assert.equal(_.isSpace.exec("sp  "), null);
assert.notEqual(_.isSpace.exec("\n sp"), null);
assert.notEqual(_.isSpace.exec("\n\n\n sp"), null);
assert.equal(_.isAtom.exec("  "), null);
assert.notEqual(_.isAtom.exec("sp  "), null);
assert.equal(_.isAtom.exec("\n sp"), null);
assert.equal(_.isAtom.exec("\n\n\n sp"), null);
assert.equal(_.isAtom.exec(";wat"), null);
assert.equal(_.isAtom.exec("\"wat\""), null);
assert.equal(_.isStr.exec("wat  "), null);
assert.equal(_.isStr.exec("\"wat "), null);
assert.equal(_.isStr.exec(" \"wat\""), null);
assert.notEqual(_.isStr.exec("\"wat \'w\' wer\" "), null);
assert.equal(_.isStr.exec(";wat "), null);
assert.equal(_.isStr.exec("   "), null);
assert.equal(_.isStr.exec("\n \"wat\""), null);
assert.notEqual(_.isStr.exec("\"a\""), null);
assert.equal(_.isStr.exec("\"./help.js\"\n                ))\n(:= obArr \"[object Array]\"\n  )")[0], "\"./help.js\"");
assert.notEqual(_.isRegex.exec("/^\/([^\\]*?|(\\.))*?\/[img]*/g"), null);
assert.notEqual(_.isRegex.exec("/^\"(([^\\]*?|(\\.))*?)\"/"), null);
assert.equal(_.isRegex.exec("/wat("), null);
assert.equal(_.isRegex.exec("  wat"), null);
assert.equal(_.isRegex.exec("wat"), null);
